### PR TITLE
Minor fix to realtime listener example code

### PR DESCRIPTION
**Pull request by RobAltena**
Same fix on English and Japanese pages.
-Remove unneeded get(). 
-Use System.exit to close down the sample.

### CODE REVIEW

**Comment by after-the-sunrise** [comment]
Thanks for the contribution. Before merging the patch, I'd like to confirm if I understand the patch correctly.

> Remove unneeded get().

By 'unneeded', do you mean that the returned result is not being referenced? The intent of this call is to block the thread until the subscription is successfully initiated, and throw an exception if something went wrong. So without this call, the initiation might silently fail.

> System.exit

The sample should gracefully terminate even without the explicit exit invocation. Or have you encountered some other issue?

**Comment by RobAltena** [comment]
> By 'unneeded', do you mean that the returned result is not being referenced? The intent of this call is to block the thread until the subscription is successfully initiated, and throw an exception if something went wrong. So without this call, the initiation might silently fail.

Everything works fine here! With or without the `get()` call. If you need a side effect of `get()` to check for a successful start up then maybe we should add a comment to that effect in the sample code? 

Even when using Pubnub without your library `System.exit()` was needed to shut down. Never considered System.Exit ungraceful though. (See this [stackoverflow discussion](https://stackoverflow.com/questions/3715967/when-should-we-call-system-exit-in-java) )

Either way: Thank you so much for putting this library up. Crispy clean code. Really enjoy working with it.

**Comment by after-the-sunrise** [comment]
> we should add a comment to that effect

Agree, maybe we can add `System.out.println` to be consistent with the other samples.

> when using Pubnub

Have you tried calling "PubNub#destroy" for clean-up? I also encountered this non-daemon thread issue in the PubNub library before, and found that this call was needed for proper termination. `Bitflyer4j#close` actually takes of this.

**Comment by RobAltena** [comment]
Will leave the update to you. Thanks for having a look.

I need `System.Exit` for any shutdown: Both using `pubnub.destroy` or using `Bitflyer4j.close`.

**Comment by after-the-sunrise** [comment]
I've improved the subscription samples in the readme docs.

**Pull request closed without merging**
